title: Seth Rait
description: >
  Student, Coder, Sailor, Musician
baseurl: ""
url: "http://sethrait.com"
author:
  twitter: sethrait
name: "Seth Rait"
markdown: Kramdown
permalink: :title
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
  - jekyll-seo-tag
google_analytics: UA-82203524-1
